idf_component_register(
    SRCS
        "app_main.c"
        "sensors/analog_sensor.c"
        "network/rs485_modem.c"
        "network/womo_rs485.c"
        "network/wifi/sensor_wifi.c"
        "network/wifi/sensor_http.c"
        "sensors/bno055_sensor.c"
        "hal/sensor_i2c_bus.c"
        "sensors/bme680_sensor.c"
        "time/rtc_pcf8523.c"
        "sensors/hx711_sensor.c"
        "time/time_sync.c"
        "network/gasbee_ble_client.c"
    INCLUDE_DIRS
        "."
        "sensors"
        "time"
        "network"
        "network/wifi"
        "hal"
        "${CMAKE_CURRENT_LIST_DIR}/../../shared"
    REQUIRES
        bsec
        bno055
        nvs_flash
        esp_wifi
        esp_netif
        esp_http_server
        mdns
        spiffs
        esp_app_format
        esp_adc
        bme680
        hx711
        i2c_bus
        json
        bt
)
